### ISSUE TITLE
讨论学迹

### ISSUE THREAD

**Issue by zgd716** [liuhuanyong/EventKGNELL#1]
大佬,可否建立个微信群,讨论相关知识(今天早上公众号刚看到,github上就有了)

**Comment by liuhuanyong** [comment]
可以的。

**Comment by liuhuanyong** [comment]
@zgd716 :已经建好，具体群，扫描readme中的二维码。

**Comment by zgd716** [comment]
> @zgd716 :已经建好，具体群，扫描readme中的二维码。

已经进群，多谢大佬
